

Imports System.Reflection.Emit

''' <summary>
''' This is a variant object that is generated by the parser. 
''' </summary>
Public Class Json

    Private _rtp As Dictionary(Of String, Object)

    Public Function GetValue(label As String) As Object
        GetValue = Nothing
        Me.Properties.TryGetValue(label, GetValue)
    End Function

    Public Sub SetValue(label As String, value As Object)
        If Me.Properties.ContainsKey(label) Then
            Me.Properties.Item(label) = value
        Else ' Me.Properties.ContainsKey(label) 
            Me.Properties.Add(label, value)
        End If ' Me.Properties.ContainsKey(label) 

    End Sub


    Public ReadOnly Property Properties As Dictionary(Of String, Object)
        Get
            If _rtp Is Nothing Then _rtp = New Dictionary(Of String, Object)
            Return _rtp
        End Get
    End Property

End Class
